; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 4
; RUN: llc -verify-machineinstrs -mcpu=pwr7 -mattr=-altivec -mtriple powerpc64-ibm-aix-xcoff \
; RUN:     --ppc-aix-enable-tlsld-heuristic=true --code-model=small < %s | FileCheck %s --check-prefixes=SMALL64,SMALL
; RUN: llc -verify-machineinstrs -mcpu=pwr7 -mattr=-altivec -mtriple powerpc64-ibm-aix-xcoff \
; RUN:     --ppc-aix-enable-tlsld-heuristic=true --code-model=large < %s | FileCheck %s --check-prefixes=LARGE64
; RUN: llc -verify-machineinstrs -mcpu=pwr7 -mattr=-altivec -mtriple powerpc-ibm-aix-xcoff \
; RUN:     --ppc-aix-enable-tlsld-heuristic=true --code-model=small < %s | FileCheck %s --check-prefixes=SMALL32,SMALL
; RUN: llc -verify-machineinstrs -mcpu=pwr7 -mattr=-altivec -mtriple powerpc-ibm-aix-xcoff \
; RUN:     --ppc-aix-enable-tlsld-heuristic=true --code-model=large < %s | FileCheck %s --check-prefixes=LARGE32

@VarTLSIE1 = internal thread_local(initialexec) global i32 42, align 4
@VarTLSIE2 = internal thread_local(initialexec) global i32 0, align 4
@VarTLSLD1 = internal thread_local(localdynamic) global i32 42, align 4
@VarTLSLD2 = internal thread_local(localdynamic) global i32 0, align 4

; Heuristic to tune function level TLS model settings:
; Use initial-exec when we have a function accessing only one TLS variable.
; Use local-dynamic when we have a function accessing a handful or more different TLS variables.

define i32 @Single_IE_USE_IE() {
; SMALL64-LABEL: Single_IE_USE_IE:
; SMALL64:       # %bb.0: # %entry
; SMALL64-NEXT:    ld 3, L..C0(2) # target-flags(ppc-tprel) @VarTLSIE1
; SMALL64-NEXT:    lwzx 3, 13, 3
; SMALL64-NEXT:    blr
;
; LARGE64-LABEL: Single_IE_USE_IE:
; LARGE64:       # %bb.0: # %entry
; LARGE64-NEXT:    addis 3, L..C0@u(2)
; LARGE64-NEXT:    ld 3, L..C0@l(3)
; LARGE64-NEXT:    lwzx 3, 13, 3
; LARGE64-NEXT:    blr
;
; SMALL32-LABEL: Single_IE_USE_IE:
; SMALL32:       # %bb.0: # %entry
; SMALL32-NEXT:    mflr 0
; SMALL32-NEXT:    stwu 1, -32(1)
; SMALL32-NEXT:    lwz 4, L..C0(2) # target-flags(ppc-tprel) @VarTLSIE1
; SMALL32-NEXT:    stw 0, 40(1)
; SMALL32-NEXT:    bla .__get_tpointer[PR]
; SMALL32-NEXT:    lwzx 3, 3, 4
; SMALL32-NEXT:    addi 1, 1, 32
; SMALL32-NEXT:    lwz 0, 8(1)
; SMALL32-NEXT:    mtlr 0
; SMALL32-NEXT:    blr
;
; LARGE32-LABEL: Single_IE_USE_IE:
; LARGE32:       # %bb.0: # %entry
; LARGE32-NEXT:    mflr 0
; LARGE32-NEXT:    stwu 1, -32(1)
; LARGE32-NEXT:    stw 0, 40(1)
; LARGE32-NEXT:    addis 3, L..C0@u(2)
; LARGE32-NEXT:    lwz 4, L..C0@l(3)
; LARGE32-NEXT:    bla .__get_tpointer[PR]
; LARGE32-NEXT:    lwzx 3, 3, 4
; LARGE32-NEXT:    addi 1, 1, 32
; LARGE32-NEXT:    lwz 0, 8(1)
; LARGE32-NEXT:    mtlr 0
; LARGE32-NEXT:    blr
entry:
  %0 = tail call align 4 ptr @llvm.threadlocal.address.p0(ptr align 4 @VarTLSIE1)
  %1 = load i32, ptr %0, align 4
  ret i32 %1
}

define i32 @Single_LD_USE_IE() {
; SMALL64-LABEL: Single_LD_USE_IE:
; SMALL64:       # %bb.0: # %entry
; SMALL64-NEXT:    ld 4, L..C1(2) # target-flags(ppc-tprel) @VarTLSLD1
; SMALL64-NEXT:    lwzx 3, 13, 4
; SMALL64-NEXT:    addi 5, 3, 42
; SMALL64-NEXT:    stwx 5, 13, 4
; SMALL64-NEXT:    blr
;
; LARGE64-LABEL: Single_LD_USE_IE:
; LARGE64:       # %bb.0: # %entry
; LARGE64-NEXT:    addis 3, L..C1@u(2)
; LARGE64-NEXT:    ld 4, L..C1@l(3)
; LARGE64-NEXT:    lwzx 3, 13, 4
; LARGE64-NEXT:    addi 5, 3, 42
; LARGE64-NEXT:    stwx 5, 13, 4
; LARGE64-NEXT:    blr
;
; SMALL32-LABEL: Single_LD_USE_IE:
; SMALL32:       # %bb.0: # %entry
; SMALL32-NEXT:    mflr 0
; SMALL32-NEXT:    stwu 1, -32(1)
; SMALL32-NEXT:    lwz 5, L..C1(2) # target-flags(ppc-tprel) @VarTLSLD1
; SMALL32-NEXT:    stw 0, 40(1)
; SMALL32-NEXT:    bla .__get_tpointer[PR]
; SMALL32-NEXT:    lwzx 4, 3, 5
; SMALL32-NEXT:    addi 6, 4, 42
; SMALL32-NEXT:    stwx 6, 3, 5
; SMALL32-NEXT:    mr 3, 4
; SMALL32-NEXT:    addi 1, 1, 32
; SMALL32-NEXT:    lwz 0, 8(1)
; SMALL32-NEXT:    mtlr 0
; SMALL32-NEXT:    blr
;
; LARGE32-LABEL: Single_LD_USE_IE:
; LARGE32:       # %bb.0: # %entry
; LARGE32-NEXT:    mflr 0
; LARGE32-NEXT:    stwu 1, -32(1)
; LARGE32-NEXT:    stw 0, 40(1)
; LARGE32-NEXT:    addis 3, L..C1@u(2)
; LARGE32-NEXT:    lwz 5, L..C1@l(3)
; LARGE32-NEXT:    bla .__get_tpointer[PR]
; LARGE32-NEXT:    lwzx 4, 3, 5
; LARGE32-NEXT:    addi 6, 4, 42
; LARGE32-NEXT:    stwx 6, 3, 5
; LARGE32-NEXT:    mr 3, 4
; LARGE32-NEXT:    addi 1, 1, 32
; LARGE32-NEXT:    lwz 0, 8(1)
; LARGE32-NEXT:    mtlr 0
; LARGE32-NEXT:    blr
entry:
  %0 = tail call align 4 ptr @llvm.threadlocal.address.p0(ptr align 4 @VarTLSLD1)
  %1 = load i32, ptr %0, align 4
  %2 = add nsw i32 42, %1
  store i32 %2, ptr %0, align 4
  ret i32 %1
}

define i32 @Multiple_IE_USE_LD() {
; SMALL64-LABEL: Multiple_IE_USE_LD:
; SMALL64:       # %bb.0: # %entry
; SMALL64-NEXT:    mflr 0
; SMALL64-NEXT:    stdu 1, -48(1)
; SMALL64-NEXT:    ld 3, L..C2(2) # target-flags(ppc-tlsldm) @"_$TLSML"
; SMALL64-NEXT:    std 0, 64(1)
; SMALL64-NEXT:    bla .__tls_get_mod[PR]
; SMALL64-NEXT:    ld 4, L..C3(2) # target-flags(ppc-tlsld) @VarTLSIE1
; SMALL64-NEXT:    ld 5, L..C4(2) # target-flags(ppc-tlsld) @VarTLSIE2
; SMALL64-NEXT:    lwzx 4, 3, 4
; SMALL64-NEXT:    lwzx 3, 3, 5
; SMALL64-NEXT:    add 3, 4, 3
; SMALL64-NEXT:    addi 1, 1, 48
; SMALL64-NEXT:    ld 0, 16(1)
; SMALL64-NEXT:    mtlr 0
; SMALL64-NEXT:    blr
;
; LARGE64-LABEL: Multiple_IE_USE_LD:
; LARGE64:       # %bb.0: # %entry
; LARGE64-NEXT:    mflr 0
; LARGE64-NEXT:    stdu 1, -48(1)
; LARGE64-NEXT:    addis 3, L..C2@u(2)
; LARGE64-NEXT:    std 0, 64(1)
; LARGE64-NEXT:    addis 6, L..C3@u(2)
; LARGE64-NEXT:    ld 3, L..C2@l(3)
; LARGE64-NEXT:    bla .__tls_get_mod[PR]
; LARGE64-NEXT:    addis 5, L..C4@u(2)
; LARGE64-NEXT:    ld 4, L..C3@l(6)
; LARGE64-NEXT:    ld 5, L..C4@l(5)
; LARGE64-NEXT:    lwzx 4, 3, 4
; LARGE64-NEXT:    lwzx 3, 3, 5
; LARGE64-NEXT:    add 3, 4, 3
; LARGE64-NEXT:    addi 1, 1, 48
; LARGE64-NEXT:    ld 0, 16(1)
; LARGE64-NEXT:    mtlr 0
; LARGE64-NEXT:    blr
;
; SMALL32-LABEL: Multiple_IE_USE_LD:
; SMALL32:       # %bb.0: # %entry
; SMALL32-NEXT:    mflr 0
; SMALL32-NEXT:    stwu 1, -32(1)
; SMALL32-NEXT:    lwz 3, L..C2(2) # target-flags(ppc-tlsldm) @"_$TLSML"
; SMALL32-NEXT:    stw 0, 40(1)
; SMALL32-NEXT:    bla .__tls_get_mod[PR]
; SMALL32-NEXT:    lwz 4, L..C3(2) # target-flags(ppc-tlsld) @VarTLSIE1
; SMALL32-NEXT:    lwz 5, L..C4(2) # target-flags(ppc-tlsld) @VarTLSIE2
; SMALL32-NEXT:    lwzx 4, 3, 4
; SMALL32-NEXT:    lwzx 3, 3, 5
; SMALL32-NEXT:    add 3, 4, 3
; SMALL32-NEXT:    addi 1, 1, 32
; SMALL32-NEXT:    lwz 0, 8(1)
; SMALL32-NEXT:    mtlr 0
; SMALL32-NEXT:    blr
;
; LARGE32-LABEL: Multiple_IE_USE_LD:
; LARGE32:       # %bb.0: # %entry
; LARGE32-NEXT:    mflr 0
; LARGE32-NEXT:    stwu 1, -32(1)
; LARGE32-NEXT:    stw 0, 40(1)
; LARGE32-NEXT:    addis 6, L..C2@u(2)
; LARGE32-NEXT:    addis 3, L..C3@u(2)
; LARGE32-NEXT:    lwz 3, L..C3@l(3)
; LARGE32-NEXT:    bla .__tls_get_mod[PR]
; LARGE32-NEXT:    lwz 4, L..C2@l(6)
; LARGE32-NEXT:    lwzx 4, 3, 4
; LARGE32-NEXT:    addis 5, L..C4@u(2)
; LARGE32-NEXT:    lwz 5, L..C4@l(5)
; LARGE32-NEXT:    lwzx 3, 3, 5
; LARGE32-NEXT:    add 3, 4, 3
; LARGE32-NEXT:    addi 1, 1, 32
; LARGE32-NEXT:    lwz 0, 8(1)
; LARGE32-NEXT:    mtlr 0
; LARGE32-NEXT:    blr
entry:
  %0 = tail call align 4 ptr @llvm.threadlocal.address.p0(ptr align 4 @VarTLSIE1)
  %1 = load i32, ptr %0, align 4
  %2 = tail call align 4 ptr @llvm.threadlocal.address.p0(ptr align 4 @VarTLSIE2)
  %3 = load i32, ptr %2, align 4
  %add = add nsw i32 %1, %3
  ret i32 %add
}

define i32 @Multiple_LD_USE_LD() {
; SMALL64-LABEL: Multiple_LD_USE_LD:
; SMALL64:       # %bb.0: # %entry
; SMALL64-NEXT:    mflr 0
; SMALL64-NEXT:    stdu 1, -48(1)
; SMALL64-NEXT:    ld 3, L..C2(2) # target-flags(ppc-tlsldm) @"_$TLSML"
; SMALL64-NEXT:    std 0, 64(1)
; SMALL64-NEXT:    bla .__tls_get_mod[PR]
; SMALL64-NEXT:    ld 4, L..C5(2) # target-flags(ppc-tlsld) @VarTLSLD1
; SMALL64-NEXT:    ld 5, L..C6(2) # target-flags(ppc-tlsld) @VarTLSLD2
; SMALL64-NEXT:    lwzx 4, 3, 4
; SMALL64-NEXT:    lwzx 3, 3, 5
; SMALL64-NEXT:    add 3, 4, 3
; SMALL64-NEXT:    addi 1, 1, 48
; SMALL64-NEXT:    ld 0, 16(1)
; SMALL64-NEXT:    mtlr 0
; SMALL64-NEXT:    blr
;
; LARGE64-LABEL: Multiple_LD_USE_LD:
; LARGE64:       # %bb.0: # %entry
; LARGE64-NEXT:    mflr 0
; LARGE64-NEXT:    stdu 1, -48(1)
; LARGE64-NEXT:    addis 3, L..C2@u(2)
; LARGE64-NEXT:    std 0, 64(1)
; LARGE64-NEXT:    addis 6, L..C5@u(2)
; LARGE64-NEXT:    ld 3, L..C2@l(3)
; LARGE64-NEXT:    bla .__tls_get_mod[PR]
; LARGE64-NEXT:    addis 5, L..C6@u(2)
; LARGE64-NEXT:    ld 4, L..C5@l(6)
; LARGE64-NEXT:    ld 5, L..C6@l(5)
; LARGE64-NEXT:    lwzx 4, 3, 4
; LARGE64-NEXT:    lwzx 3, 3, 5
; LARGE64-NEXT:    add 3, 4, 3
; LARGE64-NEXT:    addi 1, 1, 48
; LARGE64-NEXT:    ld 0, 16(1)
; LARGE64-NEXT:    mtlr 0
; LARGE64-NEXT:    blr
;
; SMALL32-LABEL: Multiple_LD_USE_LD:
; SMALL32:       # %bb.0: # %entry
; SMALL32-NEXT:    mflr 0
; SMALL32-NEXT:    stwu 1, -32(1)
; SMALL32-NEXT:    lwz 3, L..C2(2) # target-flags(ppc-tlsldm) @"_$TLSML"
; SMALL32-NEXT:    stw 0, 40(1)
; SMALL32-NEXT:    bla .__tls_get_mod[PR]
; SMALL32-NEXT:    lwz 4, L..C5(2) # target-flags(ppc-tlsld) @VarTLSLD1
; SMALL32-NEXT:    lwz 5, L..C6(2) # target-flags(ppc-tlsld) @VarTLSLD2
; SMALL32-NEXT:    lwzx 4, 3, 4
; SMALL32-NEXT:    lwzx 3, 3, 5
; SMALL32-NEXT:    add 3, 4, 3
; SMALL32-NEXT:    addi 1, 1, 32
; SMALL32-NEXT:    lwz 0, 8(1)
; SMALL32-NEXT:    mtlr 0
; SMALL32-NEXT:    blr
;
; LARGE32-LABEL: Multiple_LD_USE_LD:
; LARGE32:       # %bb.0: # %entry
; LARGE32-NEXT:    mflr 0
; LARGE32-NEXT:    stwu 1, -32(1)
; LARGE32-NEXT:    stw 0, 40(1)
; LARGE32-NEXT:    addis 6, L..C5@u(2)
; LARGE32-NEXT:    addis 3, L..C3@u(2)
; LARGE32-NEXT:    lwz 3, L..C3@l(3)
; LARGE32-NEXT:    bla .__tls_get_mod[PR]
; LARGE32-NEXT:    lwz 4, L..C5@l(6)
; LARGE32-NEXT:    lwzx 4, 3, 4
; LARGE32-NEXT:    addis 5, L..C6@u(2)
; LARGE32-NEXT:    lwz 5, L..C6@l(5)
; LARGE32-NEXT:    lwzx 3, 3, 5
; LARGE32-NEXT:    add 3, 4, 3
; LARGE32-NEXT:    addi 1, 1, 32
; LARGE32-NEXT:    lwz 0, 8(1)
; LARGE32-NEXT:    mtlr 0
; LARGE32-NEXT:    blr
entry:
  %0 = tail call align 4 ptr @llvm.threadlocal.address.p0(ptr align 4 @VarTLSLD1)
  %1 = load i32, ptr %0, align 4
  %2 = tail call align 4 ptr @llvm.threadlocal.address.p0(ptr align 4 @VarTLSLD2)
  %3 = load i32, ptr %2, align 4
  %add = add nsw i32 %1, %3
  ret i32 %add
}

define i32 @Multiple_MIX_USE_LD() {
; SMALL64-LABEL: Multiple_MIX_USE_LD:
; SMALL64:       # %bb.0: # %entry
; SMALL64-NEXT:    mflr 0
; SMALL64-NEXT:    stdu 1, -48(1)
; SMALL64-NEXT:    ld 3, L..C2(2) # target-flags(ppc-tlsldm) @"_$TLSML"
; SMALL64-NEXT:    std 0, 64(1)
; SMALL64-NEXT:    bla .__tls_get_mod[PR]
; SMALL64-NEXT:    ld 4, L..C3(2) # target-flags(ppc-tlsld) @VarTLSIE1
; SMALL64-NEXT:    ld 5, L..C5(2) # target-flags(ppc-tlsld) @VarTLSLD1
; SMALL64-NEXT:    lwzx 4, 3, 4
; SMALL64-NEXT:    lwzx 3, 3, 5
; SMALL64-NEXT:    add 3, 4, 3
; SMALL64-NEXT:    addi 1, 1, 48
; SMALL64-NEXT:    ld 0, 16(1)
; SMALL64-NEXT:    mtlr 0
; SMALL64-NEXT:    blr
;
; LARGE64-LABEL: Multiple_MIX_USE_LD:
; LARGE64:       # %bb.0: # %entry
; LARGE64-NEXT:    mflr 0
; LARGE64-NEXT:    stdu 1, -48(1)
; LARGE64-NEXT:    addis 3, L..C2@u(2)
; LARGE64-NEXT:    std 0, 64(1)
; LARGE64-NEXT:    addis 6, L..C3@u(2)
; LARGE64-NEXT:    ld 3, L..C2@l(3)
; LARGE64-NEXT:    bla .__tls_get_mod[PR]
; LARGE64-NEXT:    addis 5, L..C5@u(2)
; LARGE64-NEXT:    ld 4, L..C3@l(6)
; LARGE64-NEXT:    ld 5, L..C5@l(5)
; LARGE64-NEXT:    lwzx 4, 3, 4
; LARGE64-NEXT:    lwzx 3, 3, 5
; LARGE64-NEXT:    add 3, 4, 3
; LARGE64-NEXT:    addi 1, 1, 48
; LARGE64-NEXT:    ld 0, 16(1)
; LARGE64-NEXT:    mtlr 0
; LARGE64-NEXT:    blr
;
; SMALL32-LABEL: Multiple_MIX_USE_LD:
; SMALL32:       # %bb.0: # %entry
; SMALL32-NEXT:    mflr 0
; SMALL32-NEXT:    stwu 1, -32(1)
; SMALL32-NEXT:    lwz 3, L..C2(2) # target-flags(ppc-tlsldm) @"_$TLSML"
; SMALL32-NEXT:    stw 0, 40(1)
; SMALL32-NEXT:    bla .__tls_get_mod[PR]
; SMALL32-NEXT:    lwz 4, L..C3(2) # target-flags(ppc-tlsld) @VarTLSIE1
; SMALL32-NEXT:    lwz 5, L..C5(2) # target-flags(ppc-tlsld) @VarTLSLD1
; SMALL32-NEXT:    lwzx 4, 3, 4
; SMALL32-NEXT:    lwzx 3, 3, 5
; SMALL32-NEXT:    add 3, 4, 3
; SMALL32-NEXT:    addi 1, 1, 32
; SMALL32-NEXT:    lwz 0, 8(1)
; SMALL32-NEXT:    mtlr 0
; SMALL32-NEXT:    blr
;
; LARGE32-LABEL: Multiple_MIX_USE_LD:
; LARGE32:       # %bb.0: # %entry
; LARGE32-NEXT:    mflr 0
; LARGE32-NEXT:    stwu 1, -32(1)
; LARGE32-NEXT:    stw 0, 40(1)
; LARGE32-NEXT:    addis 6, L..C2@u(2)
; LARGE32-NEXT:    addis 3, L..C3@u(2)
; LARGE32-NEXT:    lwz 3, L..C3@l(3)
; LARGE32-NEXT:    bla .__tls_get_mod[PR]
; LARGE32-NEXT:    lwz 4, L..C2@l(6)
; LARGE32-NEXT:    lwzx 4, 3, 4
; LARGE32-NEXT:    addis 5, L..C5@u(2)
; LARGE32-NEXT:    lwz 5, L..C5@l(5)
; LARGE32-NEXT:    lwzx 3, 3, 5
; LARGE32-NEXT:    add 3, 4, 3
; LARGE32-NEXT:    addi 1, 1, 32
; LARGE32-NEXT:    lwz 0, 8(1)
; LARGE32-NEXT:    mtlr 0
; LARGE32-NEXT:    blr
entry:
  %0 = tail call align 4 ptr @llvm.threadlocal.address.p0(ptr align 4 @VarTLSIE1)
  %1 = load i32, ptr %0, align 4
  %2 = tail call align 4 ptr @llvm.threadlocal.address.p0(ptr align 4 @VarTLSLD1)
  %3 = load i32, ptr %2, align 4
  %add = add nsw i32 %1, %3
  ret i32 %add
}

declare nonnull ptr @llvm.threadlocal.address.p0(ptr nonnull)

; SMALL-LABEL: L..C0:
; SMALL-NEXT: .tc VarTLSIE1[TC],VarTLSIE1[TL]@ie
; SMALL-LABEL: L..C1:
; SMALL-NEXT: .tc VarTLSLD1[TC],VarTLSLD1[TL]@ie
; SMALL-LABEL: L..C2:
; SMALL-NEXT: .tc _Renamed..5f24__TLSML[TC],_Renamed..5f24__TLSML[TC]@ml
; SMALL-NEXT: .rename _Renamed..5f24__TLSML[TC],"_$TLSML"
; SMALL-LABEL: L..C3:
; SMALL-NEXT: .tc _Renamed..5f24__TLSLD.VarTLSIE1[TC],VarTLSIE1[TL]@ld
; SMALL-NEXT: .rename _Renamed..5f24__TLSLD.VarTLSIE1[TC],"VarTLSIE1"
; SMALL-LABEL: L..C4:
; SMALL-NEXT: .tc _Renamed..5f24__TLSLD.VarTLSIE2[TC],VarTLSIE2[UL]@ld
; SMALL-NEXT: .rename _Renamed..5f24__TLSLD.VarTLSIE2[TC],"VarTLSIE2"
; SMALL-LABEL: L..C5:
; SMALL-NEXT: .tc _Renamed..5f24__TLSLD.VarTLSLD1[TC],VarTLSLD1[TL]@ld
; SMALL-NEXT: .rename _Renamed..5f24__TLSLD.VarTLSLD1[TC],"VarTLSLD1"
; SMALL-LABEL: L..C6:
; SMALL-NEXT: .tc _Renamed..5f24__TLSLD.VarTLSLD2[TC],VarTLSLD2[UL]@ld
; SMALL-NEXT: .rename _Renamed..5f24__TLSLD.VarTLSLD2[TC],"VarTLSLD2"

; LARGE64-LABEL: L..C0:
; LARGE64-NEXT: .tc VarTLSIE1[TE],VarTLSIE1[TL]@ie
; LARGE64-LABEL: L..C1:
; LARGE64-NEXT: .tc VarTLSLD1[TE],VarTLSLD1[TL]@ie
; LARGE64-LABEL: L..C2:
; LARGE64-NEXT: .tc _Renamed..5f24__TLSML[TC],_Renamed..5f24__TLSML[TC]@ml
; LARGE64-NEXT: .rename _Renamed..5f24__TLSML[TC],"_$TLSML"
; LARGE64-LABEL: L..C3:
; LARGE64-NEXT: .tc _Renamed..5f24__TLSLD.VarTLSIE1[TE],VarTLSIE1[TL]@ld
; LARGE64-NEXT: .rename _Renamed..5f24__TLSLD.VarTLSIE1[TE],"VarTLSIE1"
; LARGE64-LABEL: L..C4:
; LARGE64-NEXT: .tc _Renamed..5f24__TLSLD.VarTLSIE2[TE],VarTLSIE2[UL]@ld
; LARGE64-NEXT: .rename _Renamed..5f24__TLSLD.VarTLSIE2[TE],"VarTLSIE2"
; LARGE64-LABEL: L..C5:
; LARGE64-NEXT: .tc _Renamed..5f24__TLSLD.VarTLSLD1[TE],VarTLSLD1[TL]@ld
; LARGE64-NEXT: .rename _Renamed..5f24__TLSLD.VarTLSLD1[TE],"VarTLSLD1"
; LARGE64-LABEL: L..C6:
; LARGE64-NEXT: .tc _Renamed..5f24__TLSLD.VarTLSLD2[TE],VarTLSLD2[UL]@ld
; LARGE64-NEXT: .rename _Renamed..5f24__TLSLD.VarTLSLD2[TE],"VarTLSLD2"

; LARGE32-LABEL: L..C0:
; LARGE32-NEXT: .tc VarTLSIE1[TE],VarTLSIE1[TL]@ie
; LARGE32-LABEL: L..C1:
; LARGE32-NEXT: .tc VarTLSLD1[TE],VarTLSLD1[TL]@ie
; LARGE32-LABEL: L..C2:
; LARGE32-NEXT: .tc _Renamed..5f24__TLSLD.VarTLSIE1[TE],VarTLSIE1[TL]@ld
; LARGE32-NEXT: .rename _Renamed..5f24__TLSLD.VarTLSIE1[TE],"VarTLSIE1"
; LARGE32-LABEL: L..C3:
; LARGE32-NEXT: .tc _Renamed..5f24__TLSML[TC],_Renamed..5f24__TLSML[TC]@ml
; LARGE32-NEXT: .rename _Renamed..5f24__TLSML[TC],"_$TLSML"
; LARGE32-LABEL: L..C4:
; LARGE32-NEXT: .tc _Renamed..5f24__TLSLD.VarTLSIE2[TE],VarTLSIE2[UL]@ld
; LARGE32-NEXT: .rename _Renamed..5f24__TLSLD.VarTLSIE2[TE],"VarTLSIE2"
; LARGE32-LABEL: L..C5:
; LARGE32-NEXT: .tc _Renamed..5f24__TLSLD.VarTLSLD1[TE],VarTLSLD1[TL]@ld
; LARGE32-NEXT: .rename _Renamed..5f24__TLSLD.VarTLSLD1[TE],"VarTLSLD1"
; LARGE32-LABEL: L..C6:
; LARGE32-NEXT: .tc _Renamed..5f24__TLSLD.VarTLSLD2[TE],VarTLSLD2[UL]@ld
; LARGE32-NEXT: .rename _Renamed..5f24__TLSLD.VarTLSLD2[TE],"VarTLSLD2"
